FROM oraclelinux:7-slim
RUN  yum -y install oracle-release-el7 && \
     yum-config-manager --enable ol7_oracle_instantclient && \
     yum -y install oracle-instantclient19.3-basiclite && \
     rm -rf /var/cache/yum
FROM node:12.14.1
RUN mkdir -p /broadcastx
WORKDIR /broadcastx
COPY ./ /broadcastx
RUN npm install
EXPOSE 3000
ENTRYPOINT ["npm","start"]
