apiVersion: v1
kind: Service
metadata:
  name: broadcastx
  labels:
    app: broadcastx
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      name: broadcastx
  selector:
    app: broadcastx
