apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broadcastx
spec:
  serviceName: "broadcastx"
  replicas: 1
  selector:
    matchLabels:
      app: broadcastx
  template:
    metadata:
      labels:
        app: broadcastx
    spec:
      volumes:
        - name: broadcastx-mysql
          hostPath:
            path: /root/broadcastxK8S/broadCastX/mysql
        - name: broadcastx
          hostPath:
            path: /root/broadcastxK8S/broadCastX
      containers:
        - name: mysql
          image: mysql
          volumeMounts:
            - name: broadcastx-mysql
              mountPath: /docker-entrypoint-initdb.d
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
        - name: broadcastx-server
          image: node
          volumeMounts:
            - name: broadcastx
              mountPath: /broadcastx
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - "-c"
            - |
              cd /broadcastx
              npm install
              npm start
          ports:
            - containerPort: 3000
              name: broadcastx
